### PR TITLE
Overrides for dune.2.8.0

### PR DESCRIPTION
**Pull request by ManasJayanth**

### CODE REVIEW

**Comment by Julow** [comment]
Hi !

We are trying to keep Odoc buildable with Esy (we have a CI job for that) and we need to upgrade to Dune 2.8 to be able to set `(package)` on libraries and cram tests (https://github.com/ocaml/odoc/pull/685).

What is the state of this PR and how can I help ?

**Comment by ManasJayanth** [comment]
Hi @Julow, this override should only be necessary if you're on ocaml < 4.08. May I have the build error logs you faced at odoc with esy?

**Comment by jonludlam** [comment]
Here's one: https://github.com/ocaml/odoc/runs/2798150715

**Comment by jonludlam** [comment]
Note that nobody has been taking care of our package.json dependencies for a while, so the problem may well be in there! However, we do try to keep odoc working from ocaml 4.02.3 onwards and this does break that particular goal - but for our CI I'd be content with a more up-to-date version being tested with esy, since ocaml-ci is testing the older versions for us.

**Comment by ManasJayanth** [comment]
I was just about to request your to update compiler in the package.json to a new compiler, but then immediately realised how important backward compatibility is - I'll try to revive this PR again in a few days. If I don't, I request you to upgrade the compiler version  > 4.8

**Comment by EduardoRFS** [comment]
@jonludlam I think it's reasonable to expect esy users to be on 4.08+, and testing only on opam the 4.02 backend, note that currently your package.json is running on 4.06 which is already not the most up to date.

**Comment by ManasJayanth** [comment]
Closing because esy users are recommened to use ocaml > 4.08

**Pull request closed without merging**
