### PR TITLE
ppx_deriving - change the .install file on Windows after build

### PR DESCRIPTION
**Pull request by ulrikstrid**

### CODE REVIEW

**Comment by ulrikstrid** [comment]
This works locally on Windows now and on the other platforms there shouldn't be any difference

**Comment by ulrikstrid** [comment]
This failed on my mac with permission denied, don't merge

**Comment by ulrikstrid** [comment]
@fdopen From what I can see the override in your opam-mingw repo doesn't do the job, is this something you have seen as well or are we doing something funny on our side?

**Review by jordwalke — APPROVED** [review]

**Comment by fdopen** [comment]
My patch only assures that it will compile for msvc and mingw.
Your problem is solved by opam, not the package description. If an install file contains executables inside the `bin` or `lib` section, opam will add the exe suffix automatically during the install step.

**Comment by ulrikstrid** [comment]
Okay, thank you @fdopen, then this sounds like a bug in how `esy` handles .install files.

@andreypopp what do you think? And should we merge this until it's fixed in `esy` as it solves my immediate issue?

**Review by jordwalke — APPROVED** [review]

**Pull request merged**
